"""
Hardcoded Contract Diff fallback. Ships in src/ so it survives any
packaging problem with fixtures/. If _load_fixtures() raises, run()
returns these 15 redlines unchanged, preserving the demo numbers and
the two pitch-line beats (auto-renewal trap, missing data-deletion).
"""
from __future__ import annotations

from typing import Any

FALLBACK_REDLINES: list[dict[str, Any]] = [
    {
        "clause_key": "auto_renewal",
        "clause_title": "Auto-Renewal",
        "severity": "high",
        "standard_text": "Subscription auto-renews for successive 12-month terms unless either party gives written notice at least thirty (30) days before the current term ends.",
        "vendor_text": "Subscription auto-renews for successive 12-month terms. Customer must provide written non-renewal notice at least ninety (90) days before the end of the current term.",
        "similarity": 0.633,
        "deviation_summary": "Vendor's non-renewal notice window is 90 days vs. our 30. Auto-renewal trap.",
        "recommended_redline": "Reduce non-renewal notice from 90 to 30 days. This is a known auto-renewal trap.",
        "embedding_backend": "fallback",
    },
    {
        "clause_key": "data_deletion",
        "clause_title": "Data Deletion on Termination",
        "severity": "high",
        "standard_text": "Vendor shall delete all Customer data within thirty (30) days of termination and provide written certification of deletion.",
        "vendor_text": "(missing from vendor MSA)",
        "similarity": 0.0,
        "deviation_summary": "Vendor MSA omits any post-termination data deletion clause entirely.",
        "recommended_redline": "MISSING CLAUSE — require 30-day data deletion on termination with written certification of deletion.",
        "embedding_backend": "fallback",
    },
    {
        "clause_key": "data_processing",
        "clause_title": "Data Processing Addendum",
        "severity": "high",
        "standard_text": "Standard SCCs and DPA attached as Exhibit A. Customer data may not be used for model training without written consent. Data residency: US-East.",
        "vendor_text": "DPA available upon request. Customer telemetry and metadata may be used to improve the Service, including model training and benchmarking, on an aggregated and de-identified basis.",
        "similarity": 0.378,
        "deviation_summary": "Vendor reserves right to train models on Customer telemetry, even aggregated.",
        "recommended_redline": "Attach DPA as Exhibit A at signing. Strike all training/benchmarking rights on Customer telemetry, aggregated or otherwise.",
        "embedding_backend": "fallback",
    },
    {
        "clause_key": "indemnification",
        "clause_title": "Indemnification",
        "severity": "high",
        "standard_text": "Vendor will defend, indemnify, and hold Customer harmless from third-party claims arising from Vendor's IP infringement, gross negligence, or willful misconduct.",
        "vendor_text": "Vendor will indemnify Customer solely for direct IP infringement claims. Indemnity excludes claims arising from Customer modifications, combinations, or open-source components.",
        "similarity": 0.5,
        "deviation_summary": "Vendor narrows indemnity to direct IP claims only; carves out modifications and OSS.",
        "recommended_redline": "Expand indemnity to gross negligence and willful misconduct. Remove broad customer-modification carve-out.",
        "embedding_backend": "fallback",
    },
    {
        "clause_key": "limitation_of_liability",
        "clause_title": "Limitation of Liability",
        "severity": "high",
        "standard_text": "Vendor's aggregate liability is capped at the greater of (a) twelve (12) months of fees paid in the trailing year or (b) $1,000,000.",
        "vendor_text": "Vendor's aggregate liability shall not exceed three (3) months of fees paid under the applicable Order Form. Excludes consequential, indirect, and lost-profits damages.",
        "similarity": 0.397,
        "deviation_summary": "Vendor caps liability at 3 months of fees vs. our 12-month / $1M floor.",
        "recommended_redline": "Restore 12-month aggregate cap or $1M, whichever is greater. Carve consequential damages only for IP indemnity and data breach.",
        "embedding_backend": "fallback",
    },
    {
        "clause_key": "price_lock",
        "clause_title": "Price Lock",
        "severity": "high",
        "standard_text": "Per-unit pricing is locked for the initial term. Year-2 and beyond price increases capped at five percent (5%) annually.",
        "vendor_text": "Vendor reserves the right to adjust per-unit pricing at each renewal at vendor's then-current list rates.",
        "similarity": 0.369,
        "deviation_summary": "Vendor reserves unilateral renewal price increases; no cap.",
        "recommended_redline": "Cap annual price escalation at 5% post initial term. Vendor's current language permits unlimited list-rate increases.",
        "embedding_backend": "fallback",
    },
    {
        "clause_key": "warranty",
        "clause_title": "Warranty",
        "severity": "high",
        "standard_text": "Vendor warrants the Service will materially conform to documentation and be free from material defects. Sole remedy: re-performance or refund.",
        "vendor_text": "THE SERVICE IS PROVIDED \"AS IS\" WITHOUT WARRANTY OF ANY KIND. VENDOR DISCLAIMS ALL IMPLIED WARRANTIES INCLUDING MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.",
        "similarity": 0.328,
        "deviation_summary": "Vendor disclaims all warranties; service is 'AS IS' with no remedy.",
        "recommended_redline": "Replace 'AS IS' disclaimer with materially-conforms-to-documentation warranty and re-performance/refund remedy.",
        "embedding_backend": "fallback",
    },
    {
        "clause_key": "audit_rights",
        "clause_title": "Audit Rights",
        "severity": "med",
        "standard_text": "Customer may audit Vendor's compliance once per year on thirty (30) days' notice. Vendor will provide SOC 2 Type II reports annually.",
        "vendor_text": "Vendor will make available, upon written request and Vendor's reasonable discretion, the most recent SOC 2 Type II report under NDA. No on-site audit rights.",
        "similarity": 0.416,
        "deviation_summary": "Vendor offers SOC 2 on request, no on-site audit, at vendor's discretion.",
        "recommended_redline": "Restore annual on-site audit right on 30 days' notice. Require SOC 2 Type II delivered automatically, not on request.",
        "embedding_backend": "fallback",
    },
    {
        "clause_key": "ip_assignment",
        "clause_title": "IP Assignment",
        "severity": "med",
        "standard_text": "Each party retains its pre-existing IP. Customer owns all data and any derivatives. Vendor owns the Service and improvements thereto.",
        "vendor_text": "Each party retains its pre-existing IP. Vendor receives a perpetual, royalty-free license to any feedback, suggestions, or ideas provided by Customer.",
        "similarity": 0.485,
        "deviation_summary": "Vendor takes perpetual royalty-free license to Customer feedback and ideas.",
        "recommended_redline": "Strike vendor's perpetual royalty-free feedback license; Customer feedback should not transfer IP.",
        "embedding_backend": "fallback",
    },
    {
        "clause_key": "publicity",
        "clause_title": "Publicity Rights",
        "severity": "med",
        "standard_text": "(not in standard template)",
        "vendor_text": "Customer grants Vendor the right to use Customer's name and logo on Vendor's customer list and marketing materials without further consent.",
        "similarity": 0.0,
        "deviation_summary": "Vendor unilaterally claims Customer logo + name usage rights with no opt-out.",
        "recommended_redline": "Strike unilateral logo/name usage. Replace with mutual written consent per use.",
        "embedding_backend": "fallback",
    },
    {
        "clause_key": "sla_credits",
        "clause_title": "SLA Credits",
        "severity": "med",
        "standard_text": "Service Levels: 99.9% monthly uptime. Credits issued as 10% of monthly fee for each 0.1% below target, up to 100% of monthly fee.",
        "vendor_text": "Service Levels: 99.5% monthly uptime, measured on a per-region basis. Credits capped at 10% of monthly fee. Customer must request credits in writing within thirty (30) days.",
        "similarity": 0.385,
        "deviation_summary": "Vendor weakens SLA to 99.5%, caps credits at 10%, and gates on written request.",
        "recommended_redline": "Raise uptime target to 99.9%. Remove the 10% credit cap. Auto-issue credits instead of requiring written request.",
        "embedding_backend": "fallback",
    },
    {
        "clause_key": "subprocessors",
        "clause_title": "Subprocessors",
        "severity": "med",
        "standard_text": "Vendor maintains a public list of subprocessors. Customer has the right to object to new subprocessors within fifteen (15) days of notice; failure to resolve objection allows termination.",
        "vendor_text": "Vendor may engage subprocessors at its discretion. Vendor will use commercially reasonable efforts to notify Customer of material changes.",
        "similarity": 0.316,
        "deviation_summary": "Vendor controls subprocessor changes unilaterally; no Customer objection right.",
        "recommended_redline": "Add 15-day Customer objection window for new subprocessors and right to terminate if unresolved.",
        "embedding_backend": "fallback",
    },
    {
        "clause_key": "termination_for_convenience",
        "clause_title": "Termination for Convenience",
        "severity": "med",
        "standard_text": "Customer may terminate this Agreement for convenience upon sixty (60) days written notice, with a pro-rated refund of prepaid fees.",
        "vendor_text": "Customer may not terminate for convenience during any committed term. Early termination requires payment of all remaining committed fees.",
        "similarity": 0.44,
        "deviation_summary": "Vendor disallows termination during committed term; charges remaining fees.",
        "recommended_redline": "Add 60-day termination-for-convenience right with pro-rated refund of prepaid fees.",
        "embedding_backend": "fallback",
    },
    {
        "clause_key": "confidentiality",
        "clause_title": "Confidentiality",
        "severity": "low",
        "standard_text": "Confidentiality obligations survive for five (5) years after termination. Trade secrets protected indefinitely.",
        "vendor_text": "Confidentiality obligations survive for three (3) years after termination.",
        "similarity": 0.527,
        "deviation_summary": "Confidentiality term shortened to 3 years vs. our 5.",
        "recommended_redline": "Extend confidentiality survival from 3 to 5 years; trade secrets indefinite.",
        "embedding_backend": "fallback",
    },
    {
        "clause_key": "governing_law",
        "clause_title": "Governing Law & Venue",
        "severity": "low",
        "standard_text": "Delaware law. Disputes resolved by binding arbitration in San Francisco, California under AAA Commercial Rules.",
        "vendor_text": "New York law. Exclusive jurisdiction in the courts of New York County, New York. Jury trial waived.",
        "similarity": 0.321,
        "deviation_summary": "Vendor's venue is NY with jury waiver; we prefer Delaware/SF with AAA arbitration.",
        "recommended_redline": "Negotiate neutral venue (Delaware or San Francisco). Preserve right to jury trial where state law allows.",
        "embedding_backend": "fallback",
    },
]
